params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True #False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -2.3 # std = 1.
        fixed_sigma: True

    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None
    # rnn:
    #   name: lstm
    #   units: 128
    #   layers: 1
    #   before_mlp: True
    #   concat_input: True
    #   layer_norm: False


  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:Bolt10,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    ppo: True
    multi_gpu: ${....multi_gpu}
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    normalize_advantage: True
    value_bootstrap: True
    clip_actions: False
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    gamma: 0.99
    tau: 0.95
    e_clip: 0.2
    entropy_coef: 0.001
    learning_rate: 3.e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    truncate_grads: True
    grad_norm: 1.
    horizon_length: 24
    minibatch_size: 1024
    mini_epochs: 5
    critic_coef: 2
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.

    max_epochs: ${resolve_default:2000,${....max_iterations}}
    save_best_after: 100
    score_to_win: 20000
    save_frequency: 50
    print_stats: True

ppo:
  learning_rate: 0.0001
  num_mini_batches: 32
  num_learning_epochs: 10
  gamma: 0.99
  lam: 0.95
  entropy_coef: 0.01
  value_loss_coef: 0.5
  use_clipped_value_loss: True
  clip_param: 0.2
  max_grad_norm: 0.5
  use_gae: True
  use_proper_time_limits: True
  normalize_advantage: True
  reward_shaping: True
  reward_scaling: 10.0